export const CATEGORIES = [
  'All',
  'Superstar Signatures',
  'Kebabs & Breads',
  'Mughlai Gravies',
  'Biryani',
  'Desserts',
];

export const DIETS = ['Mutton', 'Chicken', 'Buff', 'Vegetarian'];

export const SPICE_LABEL = {
  1: 'Mild — aromatic, not hot',
  2: 'Medium — Awadhi warm',
  3: 'Hot — Lucknowi red chilli finish',
};

export const MENU = [
  {
    id: 'galouti-mutton',
    name: 'Legendary Mutton Galouti Kebab',
    local: 'गलौटी कबाब',
    category: 'Superstar Signatures',
    diet: 'Mutton',
    half: 180,
    full: 330,
    unit: '4 pcs / 8 pcs',
    rating: 4.9,
    reviews: 8420,
    spice: 2,
    halal: true,
    superstar: true,
    story:
      'Built for a Nawab of Awadh who had lost his teeth but not his appetite. Minced fine on a stone, rested with raw papaya, and carrying the house blend of 160 spices that has never left the family. It collapses the moment it touches your tongue.',
    note: 'Order it with the ulte tawe ka paratha. That is the whole point.',
  },
  {
    id: 'paratha-ulta-tawa',
    name: 'Ulte Tawe Ka Paratha',
    local: 'उल्टे तवे का पराठा',
    category: 'Superstar Signatures',
    diet: 'Vegetarian',
    half: 45,
    full: 80,
    unit: '1 pc / 2 pcs',
    rating: 4.8,
    reviews: 6110,
    spice: 1,
    halal: true,
    superstar: true,
    story:
      'Slapped onto the convex back of an upturned iron tawa so the layers cook without steaming. Saffron and a little milk go into the dough, which is why it comes off the tawa gold rather than brown.',
    note: 'Tear, fold, scoop. Never cut with a knife.',
  },
  {
    id: 'mutton-chaap',
    name: 'Mutton Chaap',
    local: 'मटन चाप',
    category: 'Superstar Signatures',
    diet: 'Mutton',
    half: 260,
    full: 470,
    unit: '3 pcs / 6 pcs',
    rating: 4.8,
    reviews: 4230,
    spice: 2,
    halal: true,
    superstar: true,
    story:
      'Rib chops simmered in their own stock until the meat gives way, then finished on the tawa with ghee and a dusting of the house masala. The bone is the best part; everyone in Aminabad knows this.',
    note: 'Cooked to order, adds about 15 minutes at peak hours.',
  },
  {
    id: 'chicken-korma',
    name: 'Mughlai Chicken Korma',
    local: 'मुर्ग़ कोरमा',
    category: 'Superstar Signatures',
    diet: 'Chicken',
    half: 220,
    full: 400,
    unit: 'serves 1 / serves 2',
    rating: 4.7,
    reviews: 3915,
    spice: 2,
    halal: true,
    superstar: true,
    story:
      'A white korma in the Lucknowi manner — cashew, melon seed and curd instead of tomato, perfumed with kewra at the last minute. Pale, rich, and deliberately not the orange korma served elsewhere.',
    note: 'Mop it with sheermal rather than rice.',
  },
  {
    id: 'shahi-tukda',
    name: 'Shahi Tukda',
    local: 'शाही टुकड़ा',
    category: 'Superstar Signatures',
    diet: 'Vegetarian',
    half: 90,
    full: 160,
    unit: '2 pcs / 4 pcs',
    rating: 4.8,
    reviews: 2870,
    spice: 1,
    halal: true,
    superstar: true,
    story:
      'Bread fried in ghee, soaked in saffron rabri, finished with silver leaf and slivered pistachio. The dish the royal kitchens invented so that stale bread could still arrive at a royal table.',
    note: 'Served warm. Ask for it chilled if you prefer.',
  },
  {
    id: 'phirni',
    name: 'Kesar Phirni',
    local: 'फिरनी',
    category: 'Superstar Signatures',
    diet: 'Vegetarian',
    half: 70,
    full: 130,
    unit: '1 kulhad / 2 kulhad',
    rating: 4.7,
    reviews: 2145,
    spice: 1,
    halal: true,
    superstar: true,
    story:
      'Ground rice cooked down in full-cream milk and set in earthen kulhads, which pull out just enough moisture to give it that thick, faintly clay-scented finish.',
    note: 'Set overnight. Sells out most Sundays by 9 PM.',
  },

  {
    id: 'galouti-buff',
    name: 'Buff Galouti Kebab',
    local: 'गलौटी कबाब',
    category: 'Kebabs & Breads',
    diet: 'Buff',
    half: 130,
    full: 240,
    unit: '4 pcs / 8 pcs',
    rating: 4.8,
    reviews: 5390,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'The everyday Aminabad version, and the one most regulars grew up on. Same spice blend, same stone-minced texture, gentler on the wallet.',
    note: '',
  },
  {
    id: 'shami-kebab',
    name: 'Mutton Shami Kebab',
    local: 'शामी कबाब',
    category: 'Kebabs & Breads',
    diet: 'Mutton',
    half: 150,
    full: 280,
    unit: '4 pcs / 8 pcs',
    rating: 4.6,
    reviews: 1980,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'Mince boiled with chana dal, ground, then stuffed with a mint-onion filling and shallow fried. Firmer than the galouti, and meant to be eaten with raw onion and lime.',
    note: '',
  },
  {
    id: 'seekh-kebab',
    name: 'Mutton Seekh Kebab',
    local: 'सीख कबाब',
    category: 'Kebabs & Breads',
    diet: 'Mutton',
    half: 190,
    full: 350,
    unit: '3 pcs / 6 pcs',
    rating: 4.6,
    reviews: 2260,
    spice: 3,
    halal: true,
    superstar: false,
    story:
      'Hand-pressed onto flat iron skewers over coal. Coarser mince, more chilli, more smoke — the loud cousin in a quiet family of kebabs.',
    note: '',
  },
  {
    id: 'chicken-kakori',
    name: 'Chicken Kakori Kebab',
    local: 'काकोरी कबाब',
    category: 'Kebabs & Breads',
    diet: 'Chicken',
    half: 170,
    full: 310,
    unit: '3 pcs / 6 pcs',
    rating: 4.5,
    reviews: 1440,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'From the Kakori tradition outside Lucknow, where the mince is worked until it barely holds on the skewer. Ours uses chicken thigh so it stays juicy.',
    note: '',
  },
  {
    id: 'sheermal',
    name: 'Sheermal',
    local: 'शीरमाल',
    category: 'Kebabs & Breads',
    diet: 'Vegetarian',
    half: 40,
    full: 75,
    unit: '1 pc / 2 pcs',
    rating: 4.6,
    reviews: 1620,
    spice: 1,
    halal: true,
    superstar: false,
    story:
      'A mildly sweet saffron-milk bread baked in the tandoor, originally an Iranian import that Lucknow adopted and never gave back.',
    note: '',
  },
  {
    id: 'rumali-roti',
    name: 'Rumali Roti',
    local: 'रूमाली रोटी',
    category: 'Kebabs & Breads',
    diet: 'Vegetarian',
    half: 25,
    full: 45,
    unit: '1 pc / 2 pcs',
    rating: 4.4,
    reviews: 890,
    spice: 1,
    halal: true,
    superstar: false,
    story:
      'Stretched thin enough to read through, cooked seconds a side on the inverted tawa, then folded like a handkerchief.',
    note: '',
  },

  {
    id: 'mutton-nihari',
    name: 'Mutton Nihari',
    local: 'निहारी',
    category: 'Mughlai Gravies',
    diet: 'Mutton',
    half: 240,
    full: 440,
    unit: 'serves 1 / serves 2',
    rating: 4.8,
    reviews: 3120,
    spice: 3,
    halal: true,
    superstar: false,
    story:
      'Cooked on low coal from midnight, thickened with wheat flour and finished with ginger julienne. A breakfast dish by origin, which is why it is at its best before 1 PM.',
    note: 'Limited daily batch. Kulcha sold separately.',
  },
  {
    id: 'mutton-rogan-josh',
    name: 'Awadhi Rogan Josh',
    local: 'रोगन जोश',
    category: 'Mughlai Gravies',
    diet: 'Mutton',
    half: 250,
    full: 460,
    unit: 'serves 1 / serves 2',
    rating: 4.6,
    reviews: 1710,
    spice: 3,
    halal: true,
    superstar: false,
    story:
      'Deep red from Kashmiri chilli and ratanjot rather than tomato, slow-cooked until the fat separates and floats clean on top.',
    note: '',
  },
  {
    id: 'chicken-masala',
    name: 'Murgh Masala',
    local: 'मुर्ग़ मसाला',
    category: 'Mughlai Gravies',
    diet: 'Chicken',
    half: 200,
    full: 370,
    unit: 'serves 1 / serves 2',
    rating: 4.5,
    reviews: 1290,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'The house weekday gravy — browned onion paste, curd, whole garam masala, and chicken on the bone for flavour.',
    note: '',
  },
  {
    id: 'buff-korma',
    name: 'Buff Korma',
    local: 'कोरमा',
    category: 'Mughlai Gravies',
    diet: 'Buff',
    half: 180,
    full: 330,
    unit: 'serves 1 / serves 2',
    rating: 4.5,
    reviews: 1105,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'Slow-braised until a spoon goes through it, in a curd and fried-onion gravy that leans savoury rather than sweet.',
    note: '',
  },
  {
    id: 'paneer-pasanda',
    name: 'Paneer Pasanda',
    local: 'पनीर पसंदा',
    category: 'Mughlai Gravies',
    diet: 'Vegetarian',
    half: 190,
    full: 340,
    unit: 'serves 1 / serves 2',
    rating: 4.3,
    reviews: 760,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'Paneer stuffed with khoya and nuts, then laid into a cashew gravy. Cooked in a separate section of the kitchen with separate utensils.',
    note: 'Prepared in a dedicated vegetarian station.',
  },

  {
    id: 'mutton-biryani',
    name: 'Lucknowi Mutton Biryani',
    local: 'बिरयानी',
    category: 'Biryani',
    diet: 'Mutton',
    half: 260,
    full: 480,
    unit: 'serves 1 / serves 2',
    rating: 4.7,
    reviews: 3640,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'Pukki style — meat and rice cooked separately, then layered and sealed for dum. Pale, fragrant, restrained. Not Hyderabadi, and not trying to be.',
    note: '',
  },
  {
    id: 'chicken-biryani',
    name: 'Lucknowi Chicken Biryani',
    local: 'बिरयानी',
    category: 'Biryani',
    diet: 'Chicken',
    half: 210,
    full: 390,
    unit: 'serves 1 / serves 2',
    rating: 4.6,
    reviews: 2980,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'The same dum method with chicken on the bone, finished with kewra water and a few strands of saffron milk.',
    note: '',
  },
  {
    id: 'buff-pulao',
    name: 'Yakhni Pulao',
    local: 'यख़नी पुलाव',
    category: 'Biryani',
    diet: 'Buff',
    half: 180,
    full: 340,
    unit: 'serves 1 / serves 2',
    rating: 4.4,
    reviews: 980,
    spice: 1,
    halal: true,
    superstar: false,
    story:
      'Rice cooked in strained meat stock rather than layered — lighter than biryani and the older dish of the two.',
    note: '',
  },
  {
    id: 'subz-biryani',
    name: 'Subz Dum Biryani',
    local: 'सब्ज़ बिरयानी',
    category: 'Biryani',
    diet: 'Vegetarian',
    half: 170,
    full: 310,
    unit: 'serves 1 / serves 2',
    rating: 4.2,
    reviews: 540,
    spice: 2,
    halal: true,
    superstar: false,
    story:
      'Seasonal vegetables and paneer given the full dum treatment in the vegetarian section, sealed with dough and opened at the table.',
    note: 'Prepared in a dedicated vegetarian station.',
  },

  {
    id: 'kulfi-falooda',
    name: 'Kulfi Falooda',
    local: 'कुल्फ़ी फ़ालूदा',
    category: 'Desserts',
    diet: 'Vegetarian',
    half: 80,
    full: 150,
    unit: '1 portion / 2 portions',
    rating: 4.6,
    reviews: 1310,
    spice: 1,
    halal: true,
    superstar: false,
    story:
      'Milk reduced for hours, frozen in metal moulds, scraped and served over falooda sev with rose syrup.',
    note: '',
  },
  {
    id: 'malai-gilori',
    name: 'Malai Gilori',
    local: 'मलाई गिलौरी',
    category: 'Desserts',
    diet: 'Vegetarian',
    half: 110,
    full: 200,
    unit: '2 pcs / 4 pcs',
    rating: 4.5,
    reviews: 690,
    spice: 1,
    halal: true,
    superstar: false,
    story:
      'A Lucknow speciality — sheets of clotted cream folded like a paan around a sweet filling, finished with silver leaf.',
    note: '',
  },
  {
    id: 'gulab-jamun',
    name: 'Ghee Gulab Jamun',
    local: 'गुलाब जामुन',
    category: 'Desserts',
    diet: 'Vegetarian',
    half: 60,
    full: 110,
    unit: '2 pcs / 4 pcs',
    rating: 4.4,
    reviews: 820,
    spice: 1,
    halal: true,
    superstar: false,
    story:
      'Khoya balls fried in ghee and rested in cardamom syrup until they take on the weight of it.',
    note: '',
  },
];

export const SUPERSTARS = MENU.filter((item) => item.superstar);

export function getItem(id) {
  return MENU.find((item) => item.id === id) || null;
}

export const CATERING_PACKAGES = [
  {
    id: 'kebab-counter',
    name: 'Live Kebab Counter',
    perHead: 480,
    minGuests: 40,
    includes:
      'Galouti, seekh and shami kebabs made live on the tawa, ulte tawe ka paratha, chutneys, salad.',
  },
  {
    id: 'awadhi-thali',
    name: 'Awadhi Wedding Spread',
    perHead: 950,
    minGuests: 75,
    includes:
      'Two kebabs, korma, nihari, biryani, three breads, raita, salad, and two desserts.',
  },
  {
    id: 'nawabi-royal',
    name: 'Nawabi Royal Dawat',
    perHead: 1450,
    minGuests: 100,
    includes:
      'Full signature range including mutton chaap and rogan josh, live paratha station, shahi tukda, phirni, and service staff.',
  },
  {
    id: 'veg-mughlai',
    name: 'Vegetarian Mughlai Menu',
    perHead: 620,
    minGuests: 40,
    includes:
      'Paneer pasanda, subz biryani, dal, three breads, raita and dessert, cooked in a separate vegetarian kitchen.',
  },
];

export const REVIEWS = [
  {
    name: 'Faiz Rahman',
    city: 'Chowk, Lucknow',
    rating: 5,
    date: 'August 2026',
    text: 'Forty years I have been eating here and the galouti has not moved an inch. Same counter, same smell from the lane, same paratha off the upturned tawa. Upstairs is comfortable now, but I still eat standing downstairs.',
  },
  {
    name: 'Shruti Nambiar',
    city: 'Visiting from Bengaluru',
    rating: 5,
    date: 'July 2026',
    text: 'Came at 3 PM expecting a queue and got a table upstairs in five minutes. Ordered half galouti and one paratha, then went back and ordered it twice more. The kebab genuinely does not need chewing.',
  },
  {
    name: 'Arjun Mehrotra',
    city: 'Gomti Nagar',
    rating: 4,
    date: 'September 2026',
    text: 'Nihari before noon is the move, it runs out. Parking near Nazirabad is the only real complaint — leave the car behind Prince Market and walk the last bit.',
  },
  {
    name: 'Ayesha Siddiqui',
    city: 'Aliganj',
    rating: 5,
    date: 'June 2026',
    text: 'Ordered the Nawabi Dawat for 120 guests at our nikah. Food reached warm, the kebab counter ran the whole evening, and the phirni in kulhads was what everyone messaged about afterwards.',
  },
];
